import json
import os
import shutil
import sys
from dataclasses import asdict

import numpy as np

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from A001_functions.abq_inp_file_creator import S6, StepData, data


# SIM_3100 is the eigen-analysis rerun of SIM_3002.  The physical analysis
# remains implicit dynamic; stiffness matrices are generated by the separate
# replay workflow in A001_functions.stiffness_eigen.
SIM_NUM = 3100
SOURCE_SIM = 3002
PRESSURE = 0.04 * np.sqrt(2)  # SIM_3002: 0.05656854249 MPa
MESH_FILE = 'A1000.mesh.json'
E = 20
DENSITY = 1e-6
STEP0_STABILIZATION = 2e-5
U_RAMP = -5


def create_input(replace=None):
    """Create the dynamic SIM_3100 deck corresponding to SIM_3002.

    ``replace`` may be True/False for non-interactive use.  When omitted,
    an existing simulation directory is replaced only after confirmation.
    """
    os.makedirs('I001_Results/OBJ_files', exist_ok=True)

    path = f'E001_Simulations/SIM_{SIM_NUM:03d}'
    if os.path.exists(path):
        if replace is None:
            answer = input(f"Folder '{path}' already exists. Replace it? (y/n): ").strip().lower()
            replace = answer == 'y'
        if not replace:
            print('Operation cancelled. Folder was not replaced.')
            return None
        shutil.rmtree(path)
        os.makedirs(path)
        print(f"Folder '{path}' was replaced.")
    else:
        os.makedirs(path)
        print(f"Folder '{path}' was created.")

    obj = data()
    obj.input_name = f'C001_Mesh_files/{MESH_FILE}'
    obj.periodic = 'both'
    obj.scale_x = 20.0
    obj.scale_y = 20.0
    obj.input = f'{path}/SIM_{SIM_NUM:03d}.inp'
    obj.E = E
    obj.nu = 0.3
    obj.material_model = 'neo_hookean'
    obj.t = 1
    obj.ELE_TYPE_3 = 'CPS3'
    obj.ELE_TYPE_4 = 'CPS4'
    obj.density_foam = DENSITY
    obj.fluid_cavity = """*Molecular Weight
        28.0e-6"""
    obj.physical_constants = '*Physical Constants, absolute zero=0, universal gas=8314'
    obj.gas_present = True
    obj.fluid_cavity_ratio = 1.0
    obj.initial_Temp = 273
    obj.initial_Pressure = 0.101325

    step0 = StepData(
        name='Step-0',
        solver=f"""**
    *Step, name=Step-0, nlgeom=YES, inc=99999, unsymm=YES
    *Static, stabilize, factor={STEP0_STABILIZATION}, continue=NO
    1e-5, 1., 1e-99, 0.1
    """,
        corner_xnyn_bc=[0, 0, None, None, None, None],
        corner_xpyn_bc=[None, 0, None, None, None, None],
        Pressure_BC=PRESSURE,
        time_interval_out=0.1,
        frequ_out=100,
        out_frames=100,
        restart_line='',
        ELE_OUTPUT='S11, S12, S22',
        NODES_OUTPUT='COOR1, COOR2',
        additional_outputs=["""** HISTORY OUTPUT: H-Set-y-negative
    *Output, history, time interval=0.005
    *Node Output, nset=Set-y-negative
    RF2,
    """, """** HISTORY OUTPUT: H-Energy
    *Output, history, time interval=0.005
    *Energy Output
    ALLKE, ALLSE, ALLIE, ALLSD, ALLWK
    """],
    )

    step1 = StepData(
        name='Step-1',
        solver="""**
    *Step, name=Step-1, nlgeom=YES, inc=99999, unsymm=YES
    *Dynamic, application=QUASI-STATIC, initial=NO
    1e-4, 1., 1e-99, 0.005
    """,
        new_boundary=True,
        corner_xnyn_bc=[0, 0, None, None, None, None],
        corner_xpyn_bc=[None, 0, None, None, None, None],
        BC_9999997=[None, U_RAMP, None, None, None, None],
        time_interval_out=0.005,
        frequ_out=100,
        out_frames=200,
        restart_line='',
        ELE_OUTPUT='S11, S12, S22',
        NODES_OUTPUT='COOR1, COOR2',
        additional_outputs=["""** HISTORY OUTPUT: H-Set-y-negative
    *Output, history, time interval=0.005
    *Node Output, nset=Set-y-negative
    RF2,
    """, """** HISTORY OUTPUT: H-Energy
    *Output, history, time interval=0.005
    *Energy Output
    ALLKE, ALLSE, ALLIE, ALLSD, ALLVD, ALLWK
    """],
        holes_output='',
    )

    obj.steps = [step0, step1]
    obj_path = f'I001_Results/OBJ_files/SIM_{SIM_NUM:03d}.json'
    with open(obj_path, 'w') as output:
        json.dump(asdict(obj), output, indent=4, separators=(',', ': '))

    S6(obj.input_name, obj.input, obj)
    print(f'Created dynamic SIM_{SIM_NUM} from SIM_{SOURCE_SIM} settings at P={PRESSURE:.9f} MPa')
    return obj.input


if __name__ == '__main__':
    create_input()
